# Generated by Django 4.2 on 2023-04-24 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('current_price', models.FloatField()),
                ('previous_price', models.FloatField()),
                ('in_stock', models.IntegerField()),
                ('description', models.TextField()),
                ('category', models.CharField(choices=[('FB', 'Football'), ('BB', 'Basketball'), ('VB', 'Volleyball'), ('HY', 'Hockey'), ('BM', 'Badminton'), ('TT', 'Table Tennis'), ('CS', 'Chess'), ('NB', 'Netball'), ('HB', 'Handball'), ('RB', 'Rugby')], max_length=2)),
                ('image', models.ImageField(upload_to='products')),
            ],
        ),
    ]
