# Generated by Django 4.2 on 2023-04-27 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_mychoices'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerdetails',
            name='next_of_kin_contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='contact',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='next_of_kin',
            field=models.CharField(choices=[('FT', 'Father'), ('MT', 'Mother'), ('RL', 'Relative'), ('OT', 'Other')], max_length=2),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='special_needs',
            field=models.CharField(choices=[('T', 'Yes'), ('F', 'No')], max_length=1),
        ),
    ]
