# Generated by Django 4.2 on 2023-04-30 05:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0005_alter_customerdetails_contact_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='County',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('county', models.CharField(choices=[('Baringo', 'BARINGO'), ('Bomet', 'BOMET'), ('Bungoma', 'BUNGOMA'), ('Busia', 'BUSIA'), ('Elgeyo Marakwet', 'ELGEYO MARAKWET'), ('Embu', 'EMBU'), ('Garissa', 'GARISSA'), ('Homa Bay', 'HOMA BAY'), ('Isiolo', 'ISIOLO'), ('Kajiado', 'KAJIADO'), ('Kakamega', 'KAKAMEGA'), ('Kericho', 'KERICHO'), ('Kiambu', 'KIAMBU'), ('Kilifi', 'KILIFI'), ('Kirinyaga', 'KIRINYAGA'), ('Kisii', 'KISII'), ('Kisumu', 'KISUMU'), ('Kitui', 'KITUI'), ('Kwale', 'KWALE'), ('Laikipia', 'LAIKIPIA'), ('Lamu', 'LAMU'), ('Machakos', 'MACHAKOS'), ('Makueni', 'MAKUENI'), ('Mandera', 'MANDERA'), ('Meru', 'MERU'), ('Migori', 'MIGORI'), ('Marsabit', 'MARSABIT'), ('Mombasa', 'MOMBASA'), ('Muranga', 'MURANGA'), ('Nairobi', 'NAIROBI'), ('Nakuru', 'NAKURU'), ('Nandi', 'NANDI'), ('Narok', 'NAROK'), ('Nyandarua', 'NYANDARUA'), ('Nyeri', 'NYERI'), ('Samburu', 'SAMBURU'), ('Siaya', 'SIAYA'), ('Taita Taveta', 'TAITA TAVETA'), ('Tana River', 'TANA RIVER'), ('Tharaka Nithi', 'THARAKA NITHI'), ('Trans Nzoia', 'TRANS NZOIA'), ('Turkana', 'TURKANA'), ('Uasin Gishu', 'Uasin Gishu'), ('Vihiga', 'VIHIGA'), ('Wajir', 'WAJIR'), ('West Pokot', 'WEST POKOT')], max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='customerdetails',
            name='special_needs',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=3),
        ),
        migrations.CreateModel(
            name='Town',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('town', models.CharField(max_length=50)),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.county')),
            ],
        ),
        migrations.CreateModel(
            name='CustomerAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pick_up_station', models.CharField(max_length=100)),
                ('zip_code', models.IntegerField()),
                ('contact', models.IntegerField()),
                ('county', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.county')),
                ('town', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.town')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
