# Generated by Django 4.2 on 2023-05-02 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_wishlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='flash_sale',
            field=models.BooleanField(default=False),
        ),
    ]
