# Generated by Django 4.2 on 2023-05-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_rename_razorpay_order_id_payment_inta_send_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customeraddress',
            name='selected',
            field=models.BooleanField(default=False),
        ),
    ]
