# Generated by Django 4.2 on 2023-05-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_customeraddress_selected'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orderplaced',
            old_name='paid',
            new_name='payment',
        ),
        migrations.RenameField(
            model_name='payment',
            old_name='inta_send_payment_id',
            new_name='inta_send_invoice_id',
        ),
    ]
